### PR TITLE
Fix clion debug vs release files

### LINKED ISSUE #285: Clion plugin generates CMakeFiles incorrectly
Whenever a new CMakeFile is generated using `./gradlew clion` all of the `include_directories`, `add_executable` and `add_custom_target` entries are duplicated twice. This causes Cmake to give the following errors: 

```
CMake Error at CMakeLists.txt:61 (add_executable):
  add_executable cannot create target "fake_frcUserProgram" because another
  target with the same name already exists.  The existing target is an
  executable created in source directory
```

```
CMake Error at CMakeLists.txt:63 (add_custom_target):
  add_custom_target cannot create target "frcUserProgram_build" because
  another target with the same name already exists.  The existing target is a
  custom target created in source directory
```

```
CMake Error at CMakeLists.txt:64 (add_custom_target):
  add_custom_target cannot create target "frcUserProgram_deploy" because
  another target with the same name already exists.  The existing target is a
  custom target created in source directory
```

### PR DESCRIPTION
**Pull request by ThadHouse**
Fixes #285

### CODE REVIEW

File: src/main/groovy/edu/wpi/first/gradlerio/ide/GenerateClionTask.groovy [hunk 1]
```diff
@@ -29,6 +29,7 @@ class GenerateClionTask extends DefaultTask {
         file.write("project(${project.name})\nset(CMAKE_CXX_STANDARD 14)\n\n")
 
         project.extensions.getByType(ClionExtension)._binaries.each { ClionExtension.ClionBinarySpec clionBin ->
+            println clionBin
```
Comment (JacisNonsense) [inline src/main/groovy/edu/wpi/first/gradlerio/ide/GenerateClionTask.groovy]: ?

**Comment by ThadHouse** [comment]
This should be good to go now
